### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by hanzhi713** [thecourseforum/theCourseForum2#358]
For example, https://thecourseforum.com/search?q=math gives no result. Occasionally, some search queries yield HTTP status 500. HTTP 500s are not reproducible for search queries that triggered them because they do not appear after retry.

**Comment by alex-shen1** [comment]
For reference, this is the error log we're getting in Google App Engine:

![image](https://user-images.githubusercontent.com/55100084/105105399-06b97d80-5a82-11eb-887b-38148a55bd18.png)

This issue is because there's something going on with Elasticsearch (the cloud service we use to handle our searching); the current hypothesis is simply that we need to upgrade the RAM on our cluster, but that costs money so I'm looking into a way to get around this.

**Comment by hanzhi713** [comment]
We (plannable) do everything on the front-end so we have zero cost. You can consider moving it to the front-end.

**Comment by Bartleby2718** [comment]
Maybe a permanent solution would involve adding tests for elasticsearch, as was proposed in #111.

**Comment by alex-shen1** [comment]
Upgraded our ES cluster's RAM, problem should be solved.
