### ISSUE TITLE
Add social links to sidebar footer

### ISSUE THREAD

**Issue by j-alicia-long** [thecourseforum/theCourseForum2#393]
Social media links are featured only on the landing page footer. Add them to the sidebar footer (possibly in 2x2 grid?) so we get more traffic!

![image](https://user-images.githubusercontent.com/4724192/107389709-03d00c80-6ac5-11eb-860e-cb975fd348ca.png)

**Comment by alex-shen1** [comment]
@khushic Just noticed that this issue didn't get closed automatically because you wrote `This PR closes (#393)` as opposed to `This PR closes #393`. The template was probably not clear about this, but in the future you're gonna want to have it specifically follow that syntax to let GitHub's automation do the work for us.

See this link for details: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
